name: clox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
    run:
      shell: bash
      working-directory: clox

    steps:
    - uses: actions/checkout@v3
    
    - uses: bazelbuild/setup-bazelisk@v2

    - name: Test
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel
    - run: bazel test --test_output=all //...