name: clox

on:
  push:
    paths: [ 'clox/**' ]
    branches: [ main ]
  pull_request:
    paths: [ 'clox/**' ]
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
        working-directory: clox


    steps:
    - uses: actions/checkout@v3
    
    - uses: bazelbuild/setup-bazelisk@v2

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel-${{ matrix.os }}
    
    - name: Test
      env:
        TEST_TMPDIR: "~/.cache/bazel"
      run: bazel test --test_output=all ...