name: jlox

on:
  push:
    paths: [ 'jlox/**' ]
    branches: [ main ]
  pull_request:
    paths: [ 'jlox/**' ]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file jlox/pom.xml